CREATE TABLE nfe_cfop(
	id integer primary key auto_increment,
	codigo varchar(5),
	descricao text
);

INSERT INTO nfe_cfop (codigo,descricao) VALUES 
('7205','ANULAÇÃO DE VALOR RELATIVO À AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO')
,('5205','Anulação de valor relativo a aquisição de serviço de comunicação')
,('6205','Anulação de valor relativo a aquisição de serviço de comunicação')
,('5206','Anulação de valor relativo a aquisição de serviço de transporte')
,('6206','Anulação de valor relativo a aquisição de serviço de transporte')
,('7206','Anulação de valor relativo a aquisição de serviço de transporte')
,('5207','Anulação de valor relativo à compra de energia elétrica')
,('6207','Anulação de valor relativo à compra de energia elétrica')
,('7207','Anulação de valor relativo à compra de energia elétrica')
,('1205','Anulação de valor relativo à prestação de serviço de comunicação')
,('2205','Anulação de valor relativo à prestação de serviço de comunicação')
,('3205','Anulação de valor relativo à prestação de serviço de comunicação')
,('1206','Anulação de valor relativo à prestação de serviço de transporte')
,('2206','Anulação de valor relativo à prestação de serviço de transporte')
,('3206','Anulação de valor relativo à prestação de serviço de transporte')
,('1207','Anulação de valor relativo à venda de energia elétrica')
,('2207','Anulação de valor relativo à venda de energia elétrica')
,('3207','Anulação de valor relativo à venda de energia elétrica')
,('1301','Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
,('2301','Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
,('3301','Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
,('1303','Aquisição de serviço de comunicação por estabelecimento comercial')
,('2303','Aquisição de serviço de comunicação por estabelecimento comercial')
,('1305','Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica')
,('2305','Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica')
,('1304','Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte')
,('2304','Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte')
,('1306','Aquisição de serviço de comunicação por estabelecimento de produtor rural')
,('2306','Aquisição de serviço de comunicação por estabelecimento de produtor rural')
,('1302','Aquisição de serviço de comunicação por estabelecimento industrial')
,('2302','Aquisição de serviço de comunicação por estabelecimento industrial')
,('1932','Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador')
,('2932','Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador')
,('1351','Aquisição de serviço de transporte para execução de serviço da mesma natureza')
,('2351','Aquisição de serviço de transporte para execução de serviço da mesma natureza')
,('3351','Aquisição de serviço de transporte para execução de serviço da mesma natureza')
,('1353','Aquisição de serviço de transporte por estabelecimento comercial')
,('2353','Aquisição de serviço de transporte por estabelecimento comercial')
,('3353','Aquisição de serviço de transporte por estabelecimento comercial')
,('1355','Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
,('2355','Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
,('3355','Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
,('1354','Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
,('2354','Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
,('3354','Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
,('1356','Aquisição de serviço de transporte por estabelecimento de produtor rural')
,('2356','Aquisição de serviço de transporte por estabelecimento de produtor rural')
,('3356','Aquisição de serviço de transporte por estabelecimento de produtor rural')
,('1352','Aquisição de serviço de transporte por estabelecimento industrial')
,('2352','Aquisição de serviço de transporte por estabelecimento industrial')
,('3352','Aquisição de serviço de transporte por estabelecimento industrial')
,('1933','Aquisição de serviço tributado pelo ISSQN')
,('2933','Aquisição de serviço tributado pelo ISSQN')
,('1406','Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária')
,('2406','Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária')
,('1551','Compra de bem para o ativo imobilizado')
,('2551','Compra de bem para o ativo imobilizado')
,('3551','Compra de bem para o ativo imobilizado')
,('1652','Compra de combustível ou lubrificante para comercialização')
,('2652','Compra de combustível ou lubrificante para comercialização')
,('3652','Compra de combustível ou lubrificante para comercialização')
,('1651','Compra de combustível ou lubrificante para industrialização subseqüente')
,('2651','Compra de combustível ou lubrificante para industrialização subseqüente')
,('3651','Compra de combustível ou lubrificante para industrialização subseqüente')
,('1653','Compra de combustível ou lubrificante por consumidor ou usuário final')
,('2653','Compra de combustível ou lubrificante por consumidor ou usuário final')
,('3653','Compra de combustível ou lubrificante por consumidor ou usuário final')
,('1257','Compra de energia elétrica para consumo por demanda contratada')
,('2257','Compra de energia elétrica para consumo por demanda contratada')
,('1251','Compra de energia elétrica para distribuição ou comercialização')
,('2251','Compra de energia elétrica para distribuição ou comercialização')
,('3251','Compra de energia elétrica para distribuição ou comercialização')
,('1253','Compra de energia elétrica por estabelecimento comercial')
,('2253','Compra de energia elétrica por estabelecimento comercial')
,('1256','Compra de energia elétrica por estabelecimento de produtor rural')
,('2256','Compra de energia elétrica por estabelecimento de produtor rural')
,('1252','Compra de energia elétrica por estabelecimento industrial')
,('2252','Compra de energia elétrica por estabelecimento industrial')
,('1255','Compra de energia elétrica por estabelecimento prestador de serviço de comunicação')
,('2255','Compra de energia elétrica por estabelecimento prestador de serviço de comunicação')
,('1254','Compra de energia elétrica por estabelecimento prestador de serviço de transporte')
,('2254','Compra de energia elétrica por estabelecimento prestador de serviço de transporte')
,('1556','Compra de material para uso ou consumo')
,('2556','Compra de material para uso ou consumo')
,('3556','Compra de material para uso ou consumo')
,('1118','Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem')
,('2118','Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem')
,('1407','Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária')
,('2407','Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária')
,('1403','Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('2403','Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('1117','Compra para comercialização originada de encomenda para recebimento futuro')
,('2117','Compra para comercialização originada de encomenda para recebimento futuro')
,('1113','Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil')
,('2113','Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil')
,('1121','Compra para comercialização, em venda à ordem, já recebida do vendedor remetente')
,('2121','Compra para comercialização, em venda à ordem, já recebida do vendedor remetente')
,('1102','Compra para comercialização')
,('2102','Compra para comercialização')
,('3102','Compra para comercialização')
,('1111','Compra para industrialização de mercadoria recebida anteriormente em consignação industrial')
,('2111','Compra para industrialização de mercadoria recebida anteriormente em consignação industrial')
,('1401','Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('2401','Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('2122','Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente.')
,('1122','Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente')
,('1116','Compra para industrialização originada de encomenda para recebimento futuro')
,('2116','Compra para industrialização originada de encomenda para recebimento futuro')
,('3127','Compra para industrialização sob o regime de “drawback”')
,('1120','Compra para industrialização, em venda à ordem, já recebida do vendedor remetente')
,('2120','Compra para industrialização, em venda à ordem, já recebida do vendedor remetente')
,('1101','Compra para industrialização')
,('2101','Compra para industrialização')
,('3101','Compra para industrialização')
,('1126','Compra para utilização na prestação de serviço')
,('2126','Compra para utilização na prestação de serviço')
,('3126','Compra para utilização na prestação de serviço')
,('5555','Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento')
,('6555','Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento')
,('5412','Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária')
,('6412','Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária')
,('5553','Devolução de compra de bem para o ativo imobilizado')
,('6553','Devolução de compra de bem para o ativo imobilizado')
,('7553','Devolução de compra de bem para o ativo imobilizado')
,('5661','Devolução de compra de combustível ou lubrificante adquirido para comercialização')
,('6661','Devolução de compra de combustível ou lubrificante adquirido para comercialização')
,('5660','Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente')
,('6660','Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente')
,('5662','Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final')
,('6662','Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final')
,('5556','Devolução de compra de material de uso ou consumo')
,('6556','Devolução de compra de material de uso ou consumo')
,('7556','Devolução de compra de material de uso ou consumo')
,('5411','Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('6411','Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('5202','Devolução de compra para comercialização')
,('6202','Devolução de compra para comercialização')
,('7202','Devolução de compra para comercialização')
,('2663','Entrada de combustível ou lubrificante para armazenagem')
,('5410','Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('6410','Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('5201','Devolução de compra para industrialização')
,('6201','Devolução de compra para industrialização')
,('7201','Devolução de compra para industrialização')
,('5210','Devolução de compra para utilização na prestação de serviço')
,('6210','Devolução de compra para utilização na prestação de serviço')
,('7210','Devolução de compra para utilização na prestação de serviço')
,('7211','Devolução de compras para industrialização sob o regime de “drawback”')
,('1209','Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência')
,('2209','Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência')
,('5413','Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária')
,('6413','Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária')
,('3503','Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação')
,('5503','Devolução de mercadoria recebida com fim específico de exportação')
,('6503','Devolução de mercadoria recebida com fim específico de exportação')
,('5918','Devolução de mercadoria recebida em consignação mercantil ou industrial')
,('6918','Devolução de mercadoria recebida em consignação mercantil ou industrial')
,('5209','Devolução de mercadoria recebida em transferência para comercialização')
,('6209','Devolução de mercadoria recebida em transferência para comercialização')
,('5208','Devolução de mercadoria recebida em transferência para industrialização')
,('6208','Devolução de mercadoria recebida em transferência para industrialização')
,('1918','Devolução de mercadoria remetida em consignação mercantil ou industrial')
,('2918','Devolução de mercadoria remetida em consignação mercantil ou industrial')
,('1208','Devolução de produção do estabelecimento, remetida em transferência')
,('2208','Devolução de produção do estabelecimento, remetida em transferência')
,('5921','Devolução de vasilhame ou sacaria')
,('6921','Devolução de vasilhame ou sacaria')
,('1553','Devolução de venda de bem do ativo imobilizado')
,('2553','Devolução de venda de bem do ativo imobilizado')
,('3553','Devolução de venda de bem do ativo imobilizado')
,('1661','Devolução de venda de combustível ou lubrificante destinado à comercialização')
,('2661','Devolução de venda de combustível ou lubrificante destinado à comercialização')
,('1662','Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final')
,('2662','Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final')
,('1660','Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente')
,('2660','Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente')
,('1411','Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
,('2411','Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
,('1204','Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
,('2204','Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
,('1202','Devolução de venda de mercadoria adquirida ou recebida de terceiros')
,('2202','Devolução de venda de mercadoria adquirida ou recebida de terceiros')
,('3202','Devolução de venda de mercadoria adquirida ou recebida de terceiros')
,('1410','Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
,('2410','Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
,('3211','Devolução de venda de produção do estabelecimento sob o regime de “drawback”')
,('1203','Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
,('2203','Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
,('1201','Devolução de venda de produção do estabelecimento')
,('2201','Devolução de venda de produção do estabelecimento')
,('3201','Devolução de venda de produção do estabelecimento')
,('5919','Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial')
,('6919','Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial')
,('1919','Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial')
,('2919','Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial')
,('1911','Entrada de amostra grátis')
,('2911','Entrada de amostra grátis')
,('1555','Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento')
,('2555','Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento')
,('1908','Entrada de bem por conta de contrato de comodato')
,('2908','Entrada de bem por conta de contrato de comodato')
,('1910','Entrada de bonificação, doação ou brinde')
,('2910','Entrada de bonificação, doação ou brinde')
,('1663','Entrada de combustível ou lubrificante para armazenagem')
,('1915','Entrada de mercadoria ou bem recebido para conserto ou reparo')
,('2915','Entrada de mercadoria ou bem recebido para conserto ou reparo')
,('1912','Entrada de mercadoria ou bem recebido para demonstração')
,('2912','Entrada de mercadoria ou bem recebido para demonstração')
,('1501','Entrada de mercadoria recebida com fim específico de exportação')
,('2501','Entrada de mercadoria recebida com fim específico de exportação')
,('1923','Entrada de mercadoria recebida do vendedor remetente, em venda à ordem')
,('2923','Entrada de mercadoria recebida do vendedor remetente, em venda à ordem')
,('1917','Entrada de mercadoria recebida em consignação mercantil ou industrial')
,('2917','Entrada de mercadoria recebida em consignação mercantil ou industrial')
,('1905','Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral')
,('2905','Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral')
,('1903','Entrada de mercadoria remetida para industrialização e não aplicada no referido processo')
,('2903','Entrada de mercadoria remetida para industrialização e não aplicada no referido processo')
,('1920','Entrada de vasilhame ou sacaria')
,('2920','Entrada de vasilhame ou sacaria')
,('1504','Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros')
,('2504','Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros')
,('1503','Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento')
,('2503','Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento')
,('1924','Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
,('2924','Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
,('1901','Entrada para industrialização por encomenda')
,('2901','Entrada para industrialização por encomenda')
,('7501','Exportação de mercadorias recebidas com fim específico de exportação')
,('5125','Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria.')
,('6125','Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria')
,('5124','Industrialização efetuada para outra empresa')
,('6124','Industrialização efetuada para outra empresa')
,('1125','Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria')
,('2125','Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria')
,('1124','Industrialização efetuada por outra empresa')
,('2124','Industrialização efetuada por outra empresa')
,('1604','Lançamento do crédito relativo à compra de bem para o ativo imobilizado')
,('5927','Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração')
,('5928','Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa')
,('7930','Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária')
,('3930','Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária')
,('1926','Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação')
,('5926','Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação')
,('1922','Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro')
,('2922','Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro')
,('5922','Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura')
,('6922','Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura')
,('5931','Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não')
,('6931','Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não')
,('5929','Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF')
,('6929','Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF')
,('1931','Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador')
,('2931','Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por')
,('1949','Outra entrada de mercadoria ou prestação de serviço não especificada')
,('2949','Outra entrada de mercadoria ou prestação de serviço não especificado')
,('3949','Outra entrada de mercadoria ou prestação de serviço não especificado')
,('7949','Outra saída de mercadoria ou prestação de serviço não especificado')
,('5949','Outra saída de mercadoria ou prestação de serviço não especificado')
,('6949','Outra saída de mercadoria ou prestação de serviço não especificado')
,('5303','Prestação de serviço de comunicação a estabelecimento comercial')
,('6303','Prestação de serviço de comunicação a estabelecimento comercial')
,('5305','Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica')
,('6305','Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica')
,('5304','Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte')
,('6304','Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte')
,('5306','Prestação de serviço de comunicação a estabelecimento de produtor rural')
,('6306','Prestação de serviço de comunicação a estabelecimento de produtor rural')
,('5302','Prestação de serviço de comunicação a estabelecimento industrial')
,('6302','Prestação de serviço de comunicação a estabelecimento industrial')
,('5307','Prestação de serviço de comunicação a não contribuinte')
,('6307','Prestação de serviço de comunicação a não contribuinte')
,('5301','Prestação de serviço de comunicação para execução de serviço da mesma natureza')
,('6301','Prestação de serviço de comunicação para execução de serviço da mesma natureza')
,('7301','Prestação de serviço de comunicação para execução de serviço da mesma natureza')
,('5359','Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal')
,('6359','Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal')
,('5353','Prestação de serviço de transporte a estabelecimento comercial')
,('6353','Prestação de serviço de transporte a estabelecimento comercial')
,('5355','Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica')
,('6355','Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica')
,('5354','Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação')
,('6354','Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação')
,('5356','Prestação de serviço de transporte a estabelecimento de produtor rural')
,('6356','Prestação de serviço de transporte a estabelecimento de produtor rural')
,('5352','Prestação de serviço de transporte a estabelecimento industrial')
,('6352','Prestação de serviço de transporte a estabelecimento industrial')
,('5357','Prestação de serviço de transporte a não contribuinte')
,('6357','Prestação de serviço de transporte a não contribuinte')
,('5932','Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador')
,('6932','Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador')
,('5351','Prestação de serviço de transporte para execução de serviço da mesma natureza')
,('6351','Prestação de serviço de transporte para execução de serviço da mesma natureza')
,('7358','Prestação de serviço de transporte')
,('5933','Prestação de serviço tributado pelo ISSQN')
,('6933','Prestação de serviço tributado pelo ISSQN')
,('1601','Recebimento, por transferência, de crédito de ICMS')
,('1602','Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS')
,('1605','Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa.')
,('5911','Remessa de amostra grátis')
,('6911','Remessa de amostra grátis')
,('5451','Remessa de animal e de insumo para estabelecimento produtor')
,('5554','Remessa de bem do ativo imobilizado para uso fora do estabelecimento')
,('6554','Remessa de bem do ativo imobilizado para uso fora do estabelecimento')
,('5908','Remessa de bem por conta de contrato de comodato')
,('6908','Remessa de bem por conta de contrato de comodato')
,('5657','Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento')
,('6657','Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento')
,('5415','Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária')
,('6415','Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária')
,('5502','Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação')
,('6502','Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação')
,('5917','Remessa de mercadoria em consignação mercantil ou industrial')
,('6917','Remessa de mercadoria em consignação mercantil ou industrial')
,('5915','Remessa de mercadoria ou bem para conserto ou reparo')
,('6915','Remessa de mercadoria ou bem para conserto ou reparo')
,('5912','Remessa de mercadoria ou bem para demonstração')
,('6912','Remessa de mercadoria ou bem para demonstração')
,('5914','Remessa de mercadoria ou bem para exposição ou feira')
,('6914','Remessa de mercadoria ou bem para exposição ou feira')
,('5923','Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem')
,('6923','Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem')
,('5414','Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
,('6414','Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
,('5501','Remessa de produção do estabelecimento, com fim específico de exportação')
,('6501','Remessa de produção do estabelecimento, com fim específico de exportação')
,('5920','Remessa de vasilhame ou sacaria')
,('6920','Remessa de vasilhame ou sacaria')
,('5910','Remessa em bonificação, doação ou brinde')
,('6910','Remessa em bonificação, doação ou brinde')
,('5663','Remessa para armazenagem de combustível ou lubrificante')
,('6663','Remessa para armazenagem de combustível ou lubrificante')
,('5905','Remessa para depósito fechado ou armazém geral')
,('6905','Remessa para depósito fechado ou armazém geral')
,('5924','Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
,('6924','Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
,('5901','Remessa para industrialização por encomenda')
,('6901','Remessa para industrialização por encomenda')
,('5904','Remessa para venda fora do estabelecimento')
,('6904','Remessa para venda fora do estabelecimento')
,('5666','Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem')
,('6666','Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem')
,('1603','Ressarcimento de ICMS retido por substituição tributária')
,('2603','Ressarcimento de ICMS retido por substituição tributária')
,('5603','Ressarcimento de ICMS retido por substituição tributária')
,('6603','Ressarcimento de ICMS retido por substituição tributária')
,('1451','Retorno de animal do estabelecimento produtor')
,('1554','Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento')
,('2554','Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento')
,('5909','Retorno de bem recebido por conta de contrato de comodato')
,('6909','Retorno de bem recebido por conta de contrato de comodato')
,('1909','Retorno de bem remetido por conta de contrato de comodato')
,('2909','Retorno de bem remetido por conta de contrato de comodato')
,('5664','Retorno de combustível ou lubrificante recebido para armazenagem')
,('6664','Retorno de combustível ou lubrificante recebido para armazenagem')
,('1664','Retorno de combustível ou lubrificante remetido para armazenagem')
,('2664','Retorno de combustível ou lubrificante remetido para armazenagem')
,('1452','Retorno de insumo não utilizado na produção')
,('1415','Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária')
,('2415','Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária')
,('5906','Retorno de mercadoria depositada em depósito fechado ou armazém geral')
,('6906','Retorno de mercadoria depositada em depósito fechado ou armazém geral')
,('5916','Retorno de mercadoria ou bem recebido para conserto ou reparo')
,('6916','Retorno de mercadoria ou bem recebido para conserto ou reparo')
,('5913','Retorno de mercadoria ou bem recebido para demonstração')
,('6913','Retorno de mercadoria ou bem recebido para demonstração')
,('1916','Retorno de mercadoria ou bem remetido para conserto ou reparo')
,('2916','Retorno de mercadoria ou bem remetido para conserto ou reparo')
,('1913','Retorno de mercadoria ou bem remetido para demonstração')
,('2913','Retorno de mercadoria ou bem remetido para demonstração')
,('1914','Retorno de mercadoria ou bem remetido para exposição ou feira')
,('2914','Retorno de mercadoria ou bem remetido para exposição ou feira')
,('5903','Retorno de mercadoria recebida para industrialização e não aplicada no referido processo')
,('6903','Retorno de mercadoria recebida para industrialização e não aplicada no referido processo')
,('5925','Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente')
,('6925','Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente')
,('1906','Retorno de mercadoria remetida para depósito fechado ou armazém geral')
,('2906','Retorno de mercadoria remetida para depósito fechado ou armazém geral')
,('1925','Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
,('2925','Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
,('1902','Retorno de mercadoria remetida para industrialização por encomenda')
,('2902','Retorno de mercadoria remetida para industrialização por encomenda')
,('5902','Retorno de mercadoria utilizada na industrialização por encomenda')
,('6902','Retorno de mercadoria utilizada na industrialização por encomenda')
,('1414','Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
,('2414','Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
,('1904','Retorno de remessa para venda fora do estabelecimento')
,('2904','Retorno de remessa para venda fora do estabelecimento')
,('1921','Retorno de vasilhame ou sacaria')
,('2921','Retorno de vasilhame ou sacaria')
,('5665','Retorno simbólico de combustível ou lubrificante recebido para armazenagem')
,('6665','Retorno simbólico de combustível ou lubrificante recebido para armazenagem')
,('5907','Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral')
,('6907','Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral')
,('1907','Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral')
,('2907','Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral')
,('1552','Transferência de bem do ativo imobilizado')
,('2552','Transferência de bem do ativo imobilizado')
,('5552','Transferência de bem do ativo imobilizado')
,('6552','Transferência de bem do ativo imobilizado')
,('1659','Transferência de combustível e lubrificante para comercialização')
,('2659','Transferência de combustível e lubrificante para comercialização')
,('1658','Transferência de combustível e lubrificante para industrialização')
,('2658','Transferência de combustível e lubrificante para industrialização')
,('5659','Transferência de combustível ou lubrificante adquirido ou recebido de terceiro')
,('6659','Transferência de combustível ou lubrificante adquirido ou recebido de terceiro')
,('5658','Transferência de combustível ou lubrificante de produção do estabelecimento')
,('6658','Transferência de combustível ou lubrificante de produção do estabelecimento')
,('5601','Transferência de crédito de ICMS acumulado')
,('1153','Transferência de energia elétrica para distribuição')
,('2153','Transferência de energia elétrica para distribuição')
,('5153','Transferência de energia elétrica')
,('6153','Transferência de energia elétrica')
,('5557','Transferência de material de uso ou consumo')
,('6557','Transferência de material de uso ou consumo')
,('1557','Transferência de material para uso ou consumo')
,('2557','Transferência de material para uso ou consumo')
,('5409','Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
,('6409','Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
,('5156','Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
,('6156','Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
,('5152','Transferência de mercadoria adquirida ou recebida de terceiros')
,('6152','Transferência de mercadoria adquirida ou recebida de terceiros')
,('5408','Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
,('6408','Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
,('5155','Transferência de produção do estabelecimento, que não deva por ele transitar')
,('6155','Transferência de produção do estabelecimento, que não deva por ele transitar')
,('5151','Transferência de produção do estabelecimento')
,('6151','Transferência de produção do estabelecimento')
,('5602','Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS')
,('5605','Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa')
,('1409','Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('2409','Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('1152','Transferência para comercialização')
,('2152','Transferência para comercialização')
,('1408','Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('2408','Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
,('1151','Transferência para industrialização')
,('2151','Transferência para industrialização')
,('1154','Transferência para utilização na prestação de serviço')
,('2154','Transferência para utilização na prestação de serviço')
,('5551','Venda de bem do ativo imobilizado')
,('6551','Venda de bem do ativo imobilizado')
,('7551','Venda de bem do ativo imobilizado')
,('5655','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização')
,('6655','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização')
,('5656','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final')
,('6656','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final')
,('5654','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente')
,('6654','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente')
,('7654','Venda de combustível ou lubrificante adquirido ou recebido de terceiros')
,('5652','Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização')
,('6652','Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização')
,('5653','Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final')
,('6653','Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final')
,('5651','Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente')
,('6651','Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente')
,('7651','Venda de combustível ou lubrificante de produção do estabelecimento')
,('5258','Venda de energia elétrica a não contribuinte')
,('6258','Venda de energia elétrica a não contribuinte')
,('5257','Venda de energia elétrica para consumo por demanda contratada')
,('6257','Venda de energia elétrica para consumo por demanda contratada')
,('5251','Venda de energia elétrica para distribuição ou comercialização')
,('6251','Venda de energia elétrica para distribuição ou comercialização')
,('5253','Venda de energia elétrica para estabelecimento comercial')
,('6253','Venda de energia elétrica para estabelecimento comercial')
,('5256','Venda de energia elétrica para estabelecimento de produtor rural')
,('6256','Venda de energia elétrica para estabelecimento de produtor rural')
,('5252','Venda de energia elétrica para estabelecimento industrial')
,('6252','Venda de energia elétrica para estabelecimento industrial')
,('5255','Venda de energia elétrica para estabelecimento prestador de serviço de comunicação')
,('6255','Venda de energia elétrica para estabelecimento prestador de serviço de comunicação')
,('5254','Venda de energia elétrica para estabelecimento prestador de serviço de transporte')
,('6254','Venda de energia elétrica para estabelecimento prestador de serviço de transporte')
,('7251','Venda de energia elétrica para o exterior')
,('5405','Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído')
,('5403','Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto')
,('6403','Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto')
,('5120','Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem')
,('6120','Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem')
,('5119','Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
,('6119','Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
,('5112','Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial')
,('6112','Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial')
,('5114','Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil')
,('6114','Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil')
,('5123','Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
,('6123','Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
,('6108','Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte')
,('5110','Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
,('6110','Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
,('5104','Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento')
,('6104','Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento')
,('5117','Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura')
,('6117','Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura')
,('5106','Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
,('6106','Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
,('7106','Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
,('5115','Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil')
,('6115','Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil')
,('5102','Venda de mercadoria adquirida ou recebida de terceiros')
,('6102','Venda de mercadoria adquirida ou recebida de terceiros')
,('7102','Venda de mercadoria adquirida ou recebida de terceiros')
,('6404','Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente')
,('5402','Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto')
,('6402','Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto')
,('5401','Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto')
,('6401','Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto')
,('5118','Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
,('6118','Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
,('5116','Venda de produção do estabelecimento originada de encomenda para entrega futura')
,('6116','Venda de produção do estabelecimento originada de encomenda para entrega futura')
,('5105','Venda de produção do estabelecimento que não deva por ele transitar')
,('6105','Venda de produção do estabelecimento que não deva por ele transitar')
,('5111','Venda de produção do estabelecimento remetida anteriormente em consignação industrial')
,('6111','Venda de produção do estabelecimento remetida anteriormente em consignação industrial')
,('5113','Venda de produção do estabelecimento remetida anteriormente em consignação mercantil')
,('6113','Venda de produção do estabelecimento remetida anteriormente em consignação mercantil')
,('5122','Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
,('6122','Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
,('7127','Venda de produção do estabelecimento sob o regime de “drawback”')
,('6107','Venda de produção do estabelecimento, destinada a não contribuinte')
,('5109','Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
,('6109','Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
,('5103','Venda de produção do estabelecimento, efetuada fora do estabelecimento')
,('6103','Venda de produção do estabelecimento, efetuada fora do estabelecimento')
,('7105','Venda de produção do estabelecimento, que não deva por ele transitar')
,('5101','Venda de produção do estabelecimento')
,('6101','Venda de produção do estabelecimento')
,('7101','Venda de produção do estabelecimento')
;